config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
  }

  root to: 'splash#index'

  # Defines the root path route ("/")
  # root "articles#index"

  resources :groups, only: [:index, :new, :create] do
    resources :entities, only: [:index, :new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :transactions, dependent: :destroy

  has_one_attached :icon

  validates :author, presence: true
  validates :icon, presence: true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :group

  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :entities, dependent: :destroy

  has_one_attached :icon

  validates :author, presence: true
  validates :icon, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :category

  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: :author_id
  has_many :entities, foreign_key: :author_id

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @group = Group.includes(:entities).find_by_id(params[:group_id])
    @entities = @group.entities.order(created_at: :desc)
  end

  def new
    @group = Group.find(params[:group_id])
    @entity = @group.entities.new
  end

  def create
    @group = Group.find(params[:group_id])
    @entity = @group.entities.new({ author_id: current_user.id, **entity_params })
    if @entity.save
      flash[:success] = 'Transaction was successfully added.'
      redirect_to group_entities_path(@group)
    else
      render :new
      flash[:error] = 'Error! Please check the form and try again.'
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.includes(:entities).where(author: current_user)
  end

  def new; end

  def create
    @group = current_user.groups.create(group_params)
    if @group.save
      flash[:success] = 'Group was successfully created.'
      redirect_to groups_path
    else
      flash.now[:error] = 'Error! Please check the form and try again.'
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to groups_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<header>
    <div>
        <%= link_to image_tag('back.png'), categories_path, id: "back-icon" %>
    </div>
    <h2>
        Categories
    </h2>
    <div>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
</header>

<div class="addCategory">

  <%= form_for(Category.new, url: categories_path) do |f| %>
    <div class="field mb-4 ">
        <%= f.text_field :name, placeholder: "Name", autofocus: true, autocomplete: "name", class: "form-control form-control-lg" %>
    </div>

    <div class="field mb-4">
      <%= f.file_field :icon %>
    </div>

    <div class="actions">
      <%= f.submit "Create Category", class: "btn btn-primary btn-lg btn-block splashBtn" %>
    </div>
  <% end %>

</div>

app/views/entities/index.html.erb
<header>
    <div>
        <%= link_to image_tag('back.png'), groups_path, id: "back-icon" %>
    </div>
    <h4>
        <%= @group.name %> <br/> Transaction
    </h4>
    <div>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
</header>

  <div class="gift-card">
    <p>Gift Card</p>
    <h3 class="money">$45.00</h3>
  </div>

<div class="transaction" >
    <div class="category-card mb-3" >
        <%= image_tag url_for(@group.icon), alt: "group icon" %>
        <div class="inner-card" >
            <div class="inner-card-info">
                <h3> <%= @group.name %> </h3>
                <span style="opacity: 0 ;" >
                    .
                </span>
            </div>
            <h4> <%= @group.created_at.strftime('%B %d, %Y %I:%M %p') %> </h4>
        </div>
    </div>

    <div class="transaction-group">
        <% @entities.each do |entity| %>
            <div class="transaction-card card mb-3">
                <div class="card-body">
                    <h4 class="card-title"><%= entity.name %></h4>
                    <h6 class="card-subtitle mb-2 text-muted">Amount: $<%= entity.amount %></h6>
                    <p class="card-text">Created at: <%= entity.created_at.strftime('%B %d, %Y %I:%M %p') %></p>
                </div>
            </div>
        <% end %>
        <div class="transaction-card card mb-3" style="background-color: #007BFF; color: #fff;">
            <div class="card-body">
                <h4 class="card-title">Payment</h4>
                <h4 class="card-subtitle mb-2">Total: $<%= @group.entities.sum(&:amount) %></h4>
            </div>
        </div>
    </div>
</div>

<footer>
    <div class="action">
        <%= link_to "add new transaction", new_group_entity_path(group_id: @group.id) %>
    </div>
</footer>

app/views/entities/new.html.erb
<header>
    <div>
        <%= link_to image_tag('back.png'), group_entities_path(group_id: @group.id), id: "back-icon" %>
    </div>
    <h2>
        Transaction
    </h2>
    <div>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
</header>

<%= form_for(Entity.new, url: group_entities_path(group_id: @group.id)) do |f| %>
    <div class="field tform mb-2 mt-4">
        <%= f.text_field :name, placeholder: "Name", autofocus: true, autocomplete: "name", class: "form-control form-control-lg" %>
    </div>

    <div class="field tform mb-2">
        <%= f.number_field :amount, placeholder:"Amount", autofocus: true, autocomplete: "name", class: "form-control form-control-lg" %>
    </div>

    <div class="actions">
        <%= f.submit "Add Transaction", class: "btn btn-primary btn-lg btn-block splashBtn" %>
    </div>
<% end %>

app/views/groups/index.html.erb
<div class="cat-container">
  <header class="fixed">
    <div>
      <%= image_tag 'menu.png', id: "menu-icon" %>
    </div>
    <h2>
      Categories
    </h2>
    <div>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
  </header>

  <div class="gift-card">
    <p>Gift Card</p>
    <h3 class="money">$45.00</h3>
  </div>

  <div class="category-group">
    <% @groups.each do |group| %>
      <%= link_to group_entities_path(group_id: group.id) do %>
        <div class="category-card">
          <%= image_tag url_for(group.icon), alt: "group icon" %>
          <div class="inner-card">
            <div class="inner-card-info">
              <h3><%= group.name %></h3>
              <%= content_tag :span, class: group.entities.present? ? 'money' : 'money' do %>
                <%= group.entities.present? ? "$#{group.entities.sum { |entity| entity.amount }}" : "$0" %>
              <% end %>
            </div>
            <h4><%= group.created_at.strftime('%B %d, %Y %I:%M %p') %></h4>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <footer>
    <div class="action">
        <%= link_to "Add a new category", new_group_path %>
    </div>
  </footer>
</div>

app/views/groups/new.html.erb
<header>
    <div>
        <%= link_to image_tag('back.png'), groups_path, id: "back-icon" %>
    </div>
    <h2>
        Groups
    </h2>
    <div>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
</header>

<div class="addGroup">

  <%= form_for(Group.new, url: groups_path) do |f| %>
    <div class="field tform mb-4 mt-4">
        <%= f.text_field :name, placeholder: "Name", autofocus: true, autocomplete: "name", class: "form-control form-control-lg" %>
    </div>

    <div class="field mb-4">
      <%= f.file_field :icon %>
    </div>

    <div class="actions">
      <%= f.submit "Create Group", class: "btn btn-primary btn-lg btn-block splashBtn" %>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget Pal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="custom-container">
      <% flash.each do |key, message| %>
        <div class="alert" role="alert">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

app/views/splash/index.html.erb
<div class="splash-page login-form">

  <h2 class="mb-4 mt-4 headline">Budget Pal</h2>

 <div class="form-actions">
    <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg btn-block splashBtn" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-lg text-primary btn-block splashBtn" %>
 </div>
</div>